version: 2
jobs:
  master-branch:
    working_directory: ~/spree_multi_vendor
    environment:
      RAILS_ENV: test
      DB: postgres
      BUNDLER_GEMFILE: gemfiles/spree_3_3.gemfile
    docker:
      - image: circleci/ruby:2.4.3
      - image: circleci/postgres:9.5
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake test_app

      - run: bundle exec rake

workflows:
  version: 2
  build_and_test:
    jobs:
      - master-branch
