version: 2
jobs:
  master-branch: &default
    working_directory: ~/spree_multi_vendor

    environment:
      BUNDLE_GEMFILE: gemfiles/spree_master.gemfile

    docker:
      - image: circleci/ruby:2.4.3-node-browsers
        environment:
          RAILS_ENV: test
          DB: postgres
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: spree_user
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: spree_user
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum .Environment.CIRCLE_STAGE + ".lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      # - save_cache:
      #     paths:
      #       - ./vendor/bundle
      #     key: v1-dependencies-{{ checksum "gemfiles/spree_3_3.gemfile.lock" }}

      - run: bundle exec rake test_app
      - run: bundle exec rake

  spree_3_3:
    <<: *default
    environment:
      BUNDLE_GEMFILE: gemfiles/spree_3_3.gemfile

workflows:
  version: 2
  build_and_test:
    jobs:
      - master-branch
      - spree_3_3
