require: rubocop-rspec

inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/DescribeClass:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
